# Generated by Django 5.0.4 on 2024-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='Enter Product Code')),
                ('product_name', models.CharField(max_length=50, verbose_name='Enter Product Name')),
                ('description', models.CharField(max_length=50, verbose_name='Enter Product Description')),
                ('quantity', models.IntegerField(verbose_name='Enter Product Quantity')),
                ('size', models.IntegerField(verbose_name='Enter Product Size')),
                ('expiration_date', models.DateField(verbose_name='Enter Product Expiration Date')),
                ('file', models.FilePathField()),
            ],
            options={
                'db_table': 'nb_db',
            },
        ),
    ]
