# Generated by Django 5.0.4 on 2024-08-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_products_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductForm',
        ),
    ]
