# Generated by Django 5.0.4 on 2024-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_products_productform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productform',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productform',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='productform',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productform',
            name='size',
            field=models.IntegerField(),
        ),
    ]
