# Generated by Django 5.0.4 on 2024-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_productform_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productform',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productform',
            name='product_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productform',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
